language: node_js

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false
    
env:
  global:
   - FORCE_COLOR=1

node_js:
  - "node"
  - "lts/*"
  
install:
  - yarn
  
script:
  - yarn test
    
cache:
  directories:
    - "node_modules"
    - ~/.npm

jobs:
  include:
    - stage: test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: release
      after_sucess:
        - yarn semantic-release

notifications:
  email: false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/