language: node_js

env:
  global:
   - FORCE_COLOR=1

node_js:
  - "node"
  - "lts/*"

install:
  - yarn

script:
  - yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - yarn semantic-release

cache:
  directories:
    - "node_modules"
    - ~/.npm

notifications:
  email: false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/